# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: frontend-hpa
#   namespace: {{ .Values.hpaValues.nameSpace }}
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: {{ .Values.hpaValues.nameDeployment }}
#   minReplicas: {{ .Values.hpaValues.minReplica }}
#   maxReplicas: {{ .Values.hpaValues.maxReplica }}
#   targetCPUUtilizationPercentage: 15

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 15