apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  project: default
  source:
    chart: onlineboutique
    repoURL: 721699489018.dkr.ecr.eu-west-1.amazonaws.com
    targetRevision: ${new_version_chart}
    helm:
      releaseName: onlineboutique
      valueFiles: 
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default



