name: Build Docker Image for Changed Services

on:
  push:
    branches:
      - main  # Trigger on commits to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [adservice, cartservice, userservice, orderservice, paymentservice]  # List all your services here

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build image
      run: docker build -t adservice:latest src/adservice/
    - name: List images
      run: docker image ls